//  LOAD HALAMAN PETA
// ══════════════════════════════════════════════════════════════════════════════
function loadPeta() {
  setNav('pt');
  setPage('Peta Pemetaan Kawasan Pedestrian','Peta wilayah & rute patroli Satlinmas');
  sbClose(); dChart('bar'); dChart('dnt'); dChart('tw');
  G('ct').classList.add('peta-outer-pa');
  _injectPetaStyles(); _destroyLeaflet();
  document.removeEventListener('keydown', _onKeyEsc);

  var h = '<div class="fu peta-container" id="peta-main-wrap" style="padding:0!important;position:relative">'
    +'<div style="padding:10px 14px 0;flex-shrink:0;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:8px">'
      +'<div class="peta-mode-toggle">'
        +'<button class="peta-mode-btn on" id="btn-leaflet" onclick="switchPetaMode(\'leaflet\')"><i class="fas fa-layer-group"></i> Peta Realtime</button>'
        +'<button class="peta-mode-btn" id="btn-mymaps" onclick="switchPetaMode(\'mymaps\')"><i class="fas fa-map"></i> Google My Maps</button>'
      +'</div>'
      +'<div style="display:flex;gap:6px;flex-shrink:0;align-items:center">'
        +'<button class="peta-btn" onclick="openLayerModal()" id="btn-edit-layer"><i class="fas fa-pen-to-square"></i> Edit Layer</button>'
        +'<button class="peta-btn" onclick="openPdfModal()" id="btn-print-pdf"><i class="fas fa-print"></i> Cetak PDF</button>'
        +'<a class="peta-btn" id="btn-open-mymaps" href="'+PETA_MYMAPS_URL+'" target="_blank" rel="noopener" style="display:none;text-decoration:none"><i class="fas fa-external-link-alt"></i> Buka My Maps</a>'
        +'<button class="peta-btn" id="btn-fullscreen" onclick="togglePetaFullscreen()"><i class="fas fa-expand" id="btn-fs-ico"></i> <span id="btn-fs-lbl">Layar Penuh</span></button>'
        +'<button class="peta-btn peta-btn-primary" onclick="reloadPetaActive()"><i class="fas fa-sync"></i> Refresh</button>'
      +'</div>'
    +'</div>'
    +'<div style="flex:1;padding:8px 14px;min-height:0;position:relative">'
      +'<div id="leaflet-wrap" style="height:100%;border-radius:12px;overflow:hidden;border:1px solid var(--border);box-shadow:var(--sh);position:relative">'
        +'<div id="lf-map-div" style="width:100%;height:100%"></div>'
        +'<div id="lf-loader" style="display:none;position:absolute;inset:0;background:rgba(235,239,248,.88);backdrop-filter:blur(6px);z-index:800;border-radius:12px;flex-direction:column;align-items:center;justify-content:center;gap:10px">'
          +'<div class="spw"><div class="spo"></div><div class="spi"></div></div>'
          +'<span style="font-size:.72rem;font-weight:700;color:var(--mid)">Memuat data peta...</span>'
        +'</div>'
        +'<button class="df-cam-btn" id="df-cam-btn" onclick="toggleStreetPanel()" title="Foto Lapangan"><i class="fas fa-camera"></i></button>'
        +'<div class="df-street-panel hidden" id="df-street-panel"></div>'
        +'<button class="lf-draw-toggle" id="btn-draw-toggle" onclick="toggleDrawPanel()" title="Gambar & Ukur"><i class="fas fa-pen-ruler"></i></button>'
        +'<div class="lf-draw-panel hidden" id="lf-draw-panel">'
          +'<div class="lf-draw-panel-lbl">Gambar</div>'
          +'<button class="lf-draw-item" id="btn-draw-line" onclick="startDraw(\'polyline\')"><i class="fas fa-pen-nib" style="color:#1e6fd9"></i> Garis / Rute</button>'
          +'<button class="lf-draw-item" id="btn-draw-area" onclick="startDraw(\'polygon\')"><i class="fas fa-vector-square" style="color:#7c3aed"></i> Area / Zona</button>'
          +'<div class="lf-draw-sep"></div>'
          +'<div class="lf-draw-panel-lbl">Kelola</div>'
          +'<button class="lf-draw-item" id="btn-draw-save" onclick="saveDrawings()"><i class="fas fa-floppy-disk" style="color:#0d9268"></i> Simpan</button>'
          +'<button class="lf-draw-item" onclick="loadDrawings()"><i class="fas fa-download" style="color:#d97706"></i> Muat</button>'
          +'<button class="lf-draw-item danger" onclick="clearDrawings()"><i class="fas fa-eraser" style="color:#c0392b"></i> Hapus Semua</button>'
        +'</div>'
        +'<div class="lf-meta-overlay" id="lf-meta-overlay">'
          +'<div class="lf-meta-title" id="lf-meta-title"><i class="fas fa-pen-nib"></i> Tambah Detail Gambar</div>'
          +'<div class="lf-meta-msr" id="lf-meta-msr" style="display:none"><i class="fas fa-ruler"></i><span id="lf-meta-msr-text"></span></div>'
          +'<div class="lf-meta-row">'
            +'<div><label style="font-size:.58rem;font-weight:700;color:rgba(255,255,255,.38);display:block;margin-bottom:4px;text-transform:uppercase;letter-spacing:.06em">Nama <span style="color:#c0392b">*</span></label><input class="lf-meta-input" id="lf-meta-nama" placeholder="Nama garis / area..." maxlength="80"></div>'
            +'<div><label style="font-size:.58rem;font-weight:700;color:rgba(255,255,255,.38);display:block;margin-bottom:4px;text-transform:uppercase;letter-spacing:.06em">Keterangan</label><input class="lf-meta-input" id="lf-meta-ket" placeholder="Deskripsi singkat..." maxlength="120"></div>'
          +'</div>'
          +'<label style="font-size:.58rem;font-weight:700;color:rgba(255,255,255,.38);display:block;margin-bottom:5px;text-transform:uppercase;letter-spacing:.06em">Warna</label>'
          +'<div class="lf-meta-warna-grid" id="lf-meta-warna-grid"></div>'
          +'<div class="lf-meta-color-custom"><input type="color" class="lf-meta-color-inp" id="lf-meta-color-inp" value="#1e6fd9" oninput="metaWarnaCustom(this.value)"><span class="lf-meta-color-lbl" id="lf-meta-color-lbl">#1e6fd9</span></div>'
          +'<div class="lf-meta-actions"><button class="lf-meta-btn-ok" onclick="confirmDrawMeta()"><i class="fas fa-check"></i> Tambahkan ke Peta</button><button class="lf-meta-btn-cancel" onclick="cancelDrawMeta()">Batal</button></div>'
        +'</div>'
        +'<div class="lf-save-note" id="lf-save-note">Disimpan!</div>'
      +'</div>'
      +'<div id="mymaps-wrap" style="height:100%;position:relative;border-radius:12px;overflow:hidden;border:1px solid var(--border);box-shadow:var(--sh);display:none">'
        +'<div class="peta-map-shimmer" id="peta-shimmer"><div class="peta-map-shimmer-ico"><i class="fas fa-map-location-dot"></i></div><p>Memuat peta interaktif...</p></div>'
        +'<div style="position:absolute;inset:0;overflow:hidden;border-radius:12px"><iframe id="peta-frame" src="'+PETA_EMBED_URL+'" allowfullscreen="" loading="eager" referrerpolicy="no-referrer-when-downgrade" onload="onPetaFrameLoad()" style="position:absolute;top:-60px;left:0;width:100%;height:calc(100% + 60px);border:none;display:block;opacity:0;transition:opacity .4s"></iframe></div>'
      +'</div>'
    +'</div>'
    +'<div id="peta-legend-bar" style="padding:0 14px 10px;flex-shrink:0"><div class="peta-lf-legend"><div class="peta-lf-legend-title"><i class="fas fa-circle-info" style="color:var(--blue)"></i> Keterangan Layer</div>'+_buildLegendHtml()+'</div></div>'
  +'</div>'
  +'<div class="pdf-render-overlay" id="pdf-render-overlay">'
    +'<div class="pdf-render-spinner"></div>'
    +'<div class="pdf-render-txt" id="pdf-render-txt">Menyiapkan render...</div>'
    +'<div class="pdf-render-sub" id="pdf-render-sub">Mohon tunggu</div>'
    +'<div class="pdf-render-progress"><div class="pdf-render-bar" id="pdf-render-bar"></div></div>'
  +'</div>'
  +'<div class="foto-ov" id="foto-ov">'
    +'<div class="foto-modal">'
      +'<div class="foto-hd" id="foto-hd"></div>'
      +'<div class="foto-filter">'
        +'<span class="foto-filter-lbl">Filter:</span>'
        +'<input type="date" class="foto-date" id="foto-date-from"><span style="color:var(--muted);font-size:.65rem">—</span><input type="date" class="foto-date" id="foto-date-to">'
        +'<select class="foto-rad" id="foto-radius" onchange="refreshFotoModal()">'
          +'<option value="100">100 m</option><option value="250">250 m</option><option value="500">500 m</option>'
          +'<option value="1000" selected>1 km</option><option value="2000">2 km</option>'
        +'</select>'
        +'<button class="foto-search" onclick="refreshFotoModal()"><i class="fas fa-search"></i> Cari</button>'
        +'<button class="foto-reset" onclick="resetFotoFilter()"><i class="fas fa-rotate-left"></i></button>'
      +'</div>'
      +'<div class="foto-body" id="foto-body"></div>'
    +'</div>'
  +'</div>'
  +'<div class="img-lb-ov" id="img-lb-ov">'
    +'<button class="img-lb-close" onclick="closeLb()"><i class="fas fa-times"></i></button>'
    +'<img class="img-lb-img" id="img-lb-img" src="" alt="">'
    +'<div class="img-lb-name" id="img-lb-name"></div>'
    +'<a class="img-lb-drv" id="img-lb-drv" href="#" target="_blank" rel="noopener" style="display:none"><i class="fas fa-external-link-alt"></i> Buka di Google Drive</a>'
  +'</div>'
  +'<div class="pdf-ov" id="pdf-ov">'
    +'<div class="pdf-modal">'
      +'<div class="pdf-mhd">'
        +'<div class="pdf-mtitle"><i class="fas fa-file-pdf" style="color:#c0392b"></i> Pratinjau &amp; Cetak Laporan Peta</div>'
        +'<div class="pdf-macts">'
          +'<button class="bg2" onclick="closePdfModal()"><i class="fas fa-times"></i> Tutup</button>'
          +'<button class="bg2" id="btn-pdf-print" onclick="execPrint()"><i class="fas fa-print"></i> Cetak</button>'
          +'<button class="bp" id="btn-pdf-dl" onclick="execDownload()"><i class="fas fa-download"></i> Unduh PDF</button>'
        +'</div>'
      +'</div>'
      +'<div class="pdf-mbody">'
        +'<div class="pdf-opts" id="pdf-opts-panel"></div>'
        +'<div class="pdf-map-area">'
          +'<div class="pdf-map-banner">'
            +'<div class="pdf-map-banner-txt"><i class="fas fa-circle-info"></i> Atur tampilan peta (pan, zoom), lalu cetak/unduh PDF</div>'
            +'<div style="display:flex;gap:6px;flex-shrink:0;align-items:center">'
              +'<button class="bg2" style="font-size:.62rem;padding:4px 10px" onclick="fitPdfMapBounds()"><i class="fas fa-expand-arrows-alt"></i> Fit Semua</button>'
              +'<div style="display:flex;gap:3px;align-items:center">'
                +'<button class="bg2" style="font-size:.62rem;padding:4px 7px;min-width:28px" onclick="if(_pdfMap)_pdfMap.zoomIn()"><i class="fas fa-plus"></i></button>'
                +'<button class="bg2" style="font-size:.62rem;padding:4px 7px;min-width:28px" onclick="if(_pdfMap)_pdfMap.zoomOut()"><i class="fas fa-minus"></i></button>'
                +'<button class="bg2" style="font-size:.62rem;padding:4px 7px;min-width:28px" onclick="if(_pdfMap)_pdfMap.panBy([0,-120])"><i class="fas fa-chevron-up"></i></button>'
                +'<button class="bg2" style="font-size:.62rem;padding:4px 7px;min-width:28px" onclick="if(_pdfMap)_pdfMap.panBy([0,120])"><i class="fas fa-chevron-down"></i></button>'
                +'<button class="bg2" style="font-size:.62rem;padding:4px 7px;min-width:28px" onclick="if(_pdfMap)_pdfMap.panBy([-120,0])"><i class="fas fa-chevron-left"></i></button>'
                +'<button class="bg2" style="font-size:.62rem;padding:4px 7px;min-width:28px" onclick="if(_pdfMap)_pdfMap.panBy([120,0])"><i class="fas fa-chevron-right"></i></button>'
              +'</div>'
            +'</div>'
          +'</div>'
          +'<div class="pdf-map-frame"><div id="pdf-map-preview"></div></div>'
        +'</div>'
      +'</div>'
    +'</div>'
  +'</div>';

  G('ct').innerHTML = h;
  _buildMetaSwatches();
  document.addEventListener('keydown', _onKeyEsc);
  _initLeaflet();
}

function _buildLegendHtml() {
  return SIMBOL_DEF.map(function(it) {
    return '<div class="peta-lf-leg-item"><i class="fas '+it.ico+'" style="color:'+it.warna+';font-size:.72rem"></i>'+it.label+'</div>';
  }).join('');
}

// ══════════════════════════════════════════════════════════════════════════════
